haikus = [
    "Brise sur l'étang\nDes cercles dans l’eau tranquille\nLe silence chante",
    "Feuilles en torrent\nLe vent écrit sur la peau\nL’automne s’endort",
    "Neige au matin clair\nUn merle fend le silence\nL’empreinte s’efface",
    "Soleil au couchant\nLes herbes se penchent, douces\nDernier souffle chaud",
    "Grain de riz tombé\nSur la table il reste seul\nComme un mot perdu",
    "Sakura en pluie\nDes pétales sur la joue\nRêver éveillé",
    "Froideur de la nuit\nSous la lune un chat miaule\nOmbres en silence",
    "Craquement du bois\nLe feu dans l’âtre respire\nTemps suspend son pas",
    "Brume dans le val\nUn pas trouble la rosée\nOdeur de matin",
    "Coquillage vide\nMurmu­res dans l’écho creux\nVoix du large loin",
    "Ruisseau solitaire\nCaressant les pierres lisses\nMurmures anciens",
    "Papillon errant\nSur la branche immobile\nLa paix s’installe",
    "Champ sous le grand ciel\nUn oiseau trace un sillon\nLibre comme l’air",
    "Tasse de thé froid\nSur le bord de la fenêtre\nAttente paisible",
    "Gouttes sur la tôle\nTambour du monde qui pleure\nChant d’un soir d’été",
    "Grillon obstiné\nDans l’herbe encore mouillée\nL’écho le prolonge",
    "Trace sur le givre\nUne main cherchait l’oubli\nEt l’a rencontré",
    "Pluie d’averse brève\nSous le toit une colombe\nTremble, mais attend",
    "Lanterne qui penche\nSous le vent chargé de cris\nFête terminée",
    "Soleil sur la joue\nLe sentier n’a pas d’adresse\nSeulement le pas",
    "Pétale tombé\nLe monde n’a pas bronché\nTout reste fragile",
    "Nuage épanché\nSur la ville sans regard\nLarmes invisibles",
    "Chuchotis du blé\nLe vent passe sans s’arrêter\nMais tout a vibré",
    "Matin en frissons\nCigale muette au sol\nDernier chant d’hier",
    "Givre sur la vitre\nL’enfant trace des étoiles\nVoyage en silence",
    "Chaudron qui murmure\nSoupe d’ailes et de rumeurs\nVieilles recettes",
    "Sur un banc usé\nUn vieil homme compte les pas\nDes jours oubliés",
    "Étoile filante\nUn vœu glisse sans témoin\nTout reste pareil",
    "Vent dans la haie sèche\nComme une main sur le dos\nSouvenir furtif",
    "Ver luisant du soir\nDans la paume un peu de nuit\nEt d’émerveillement",
    "Flaque en plein midi\nReflet d’un ciel en morceaux\nUn monde inversé",
    "Soupir de bambou\nSous la neige alourdi\nIl ploie mais chante",
    "Vieil arbre sans feuilles\nLe corbeau vient, repart\nCycle éternel",
    "Chemin de galets\nMes pieds trouvent le silence\nPierre après pierre",
    "Rêve en plein midi\nLe chat dort contre un coussin\nSouffle harmonieux",
    "Rame sous la brume\nUn cri fend la solitude\nPuis plus rien ne vient",
    "Là, un fil d’argent\nL’araignée l’a tendu seul\nVers l’infini gris",
    "Rond d’enfant tracé\nDans la poussière du mur\nSouvenir d’été",
    "Soupe de châtaignes\nAu feu de bois crépitant\nMains pleines d’hiver",
    "Un clocher lointain\nDivise le temps du vent\nPause dans le flux",
    "Galet dans la main\nPoli comme un souvenir\nEt aussi muet",
    "Un pont de fortune\nSur l’eau vive de l’enfance\nRire suspendu",
    "Tremblement de l’eau\nUn poisson fuit l’ombre noire\nInquiète beauté",
    "Le coq a chanté\nMais la nuit ne s’en va pas\nMatin fatigué",
    "Sable chaud aux pieds\nLe sel colle à la paupière\nSouvenir marin",
    "Une bougie fond\nSon silence éclaire l’ombre\nTout se recueille",
    "Panier renversé\nDes pommes roulent au sol\nComme des regrets",
    "Silence de plomb\nUn avion raye le ciel\nTemps figé en deux",
    "Papier qui s’envole\nEmportant un mot griffé\nPersonne ne lit",
    "Le thé refroidi\nUn regard fixe la pluie\nEt ne voit que lui"
]
